create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
create table projetodsp.comentarios (id varchar(255) not null, post_id varchar(255), usuario_id varchar(255), primary key (id));
create table projetodsp.posts (id varchar(255) not null, usuario_id varchar(255), primary key (id));
create table projetodsp.usuarios (rate float(53), bio varchar(255), email varchar(255) not null unique, id varchar(255) not null, name varchar(255), password varchar(255) not null, primary key (id));
alter table if exists projetodsp.comentarios add constraint FKakyu93p9g5jcjfufxujiunr30 foreign key (post_id) references projetodsp.posts;
alter table if exists projetodsp.comentarios add constraint FKdts62yj83qe3k748cgcjvm48r foreign key (usuario_id) references projetodsp.usuarios;
alter table if exists projetodsp.posts add constraint FKsw0f5g0937m4w1rmmpmbvoyev foreign key (usuario_id) references projetodsp.usuarios;
