INSERT INTO comentarios (corpo, data_de_criacao, usuario_id, post_id)
VALUES
    ('Ótimo artigo! Muito informativo e bem explicado.', CURRENT_TIMESTAMP, 4, 5),
    ('Tenho interesse em aprender mais sobre desenvolvimento ágil. Alguma recomendação de leitura?', CURRENT_TIMESTAMP, 6, 6),
    ('A Internet das Coisas é fascinante! Estou ansioso para ver como ela continuará a evoluir.', CURRENT_TIMESTAMP, 8, 7),
    ('Dicas valiosas para construir APIs eficientes. Obrigado por compartilhar!', CURRENT_TIMESTAMP, 10, 8),
    ('Cibersegurança é um tópico crucial nos dias de hoje. Gostaria de ver mais conteúdos sobre o assunto.', CURRENT_TIMESTAMP, 12, 9),
    ('JavaScript é uma linguagem incrível! Adorei a análise das mudanças recentes.', CURRENT_TIMESTAMP, 14, 10),
    ('Estou intrigado pelo Machine Learning. Alguma sugestão para começar?', CURRENT_TIMESTAMP, 16, 11),
    ('Redes de computadores são fascinantes! Obrigado por compartilhar esse conhecimento.', CURRENT_TIMESTAMP, 18, 12),
    ('Usabilidade é crucial para o sucesso de produtos. Excelentes dicas!', CURRENT_TIMESTAMP, 20, 13),
    ('Big Data está transformando muitas indústrias. Gostaria de ver mais casos de uso.', CURRENT_TIMESTAMP, 22, 14),
    ('Scrum é uma ferramenta poderosa no gerenciamento de projetos. Utilizo no meu trabalho diário.', CURRENT_TIMESTAMP, 24, 15),
    ('Realidade virtual é um campo emocionante! Gostaria de aprender mais sobre suas aplicações práticas.', CURRENT_TIMESTAMP, 26, 16),
    ('React Native é uma escolha sólida para desenvolvimento mobile. Obrigado pelas dicas!', CURRENT_TIMESTAMP, 28, 17),
    ('Dicas valiosas para otimizar a performance de websites. Isso é crucial para a experiência do usuário.', CURRENT_TIMESTAMP, 30, 18),
    ('Computação em nuvem é o futuro! Como você vê essa tecnologia evoluindo?', CURRENT_TIMESTAMP, 1, 19),
    ('Python é minha linguagem favorita! Gostaria de ver mais tutoriais avançados.', CURRENT_TIMESTAMP, 3, 20),
    ('Ética em IA é um tema importante. Como você vê o papel das empresas nesse contexto?', CURRENT_TIMESTAMP, 5, 21),
    ('Segurança web é uma preocupação constante. Obrigado pelas práticas recomendadas!', CURRENT_TIMESTAMP, 7, 22),
    ('Experiência do usuário é crucial para aplicativos móveis. Alguma dica específica para iOS?', CURRENT_TIMESTAMP, 9, 23),
    ('Blockchain tem um grande potencial! Como você vê seu impacto nos serviços financeiros?', CURRENT_TIMESTAMP, 11, 24),
    ('Desenvolvimento de jogos é uma área que sempre me interessou. Alguma recomendação de engine?', CURRENT_TIMESTAMP, 13, 25),
    ('C# é uma linguagem versátil. Gostaria de ver mais sobre seus recursos avançados.', CURRENT_TIMESTAMP, 15, 26),
    ('Segurança em IoT é uma preocupação crescente. Como você aborda esse desafio?', CURRENT_TIMESTAMP, 17, 27)